apiVersion: v1
kind: Service
metadata:
  name: forge1-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: forge1-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: forge1-backend
  ports:
    - name: http
      port: 8000
      targetPort: {{ .Values.backend.port }}

