apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge1-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: forge1-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: forge1-backend
  template:
    metadata:
      labels:
        app: forge1-backend
        prometheus.io/scrape: "{{ ternary "true" "false" .Values.backend.metrics.enabled }}"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.backend.port }}"
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.backend.env.LOG_LEVEL | quote }}
            - name: FORGE1_ENV
              value: {{ .Values.backend.env.FORGE1_ENV | quote }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

