# forge1/docker-compose.dev.yml
# Development Docker Compose configuration with hot reloading

version: '3.8'

services:
  # Backend service for development
  forge1-backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    container_name: forge1-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - FORGE1_ENV=development
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      - ./backend:/app:rw
      - ../Multi-Agent-Custom-Automation-Engine-Solution-Accelerator/src/backend:/app/microsoft_backend:ro
    networks:
      - forge1-dev-network
    command: ["uvicorn", "forge1.core.app_kernel:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/forge1"]
    depends_on:
      - redis-dev
      - postgres-dev

  # Frontend service for development
  forge1-frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    container_name: forge1-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    networks:
      - forge1-dev-network
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - forge1-backend-dev

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    container_name: forge1-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - forge1-dev-network

  # PostgreSQL for development
  postgres-dev:
    image: postgres:15-alpine
    container_name: forge1-postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=forge1_dev
      - POSTGRES_USER=forge1_dev_user
      - POSTGRES_PASSWORD=forge1_dev_pass
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - forge1-dev-network

networks:
  forge1-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local